# Arewa Data Science Academy
## Deep Learning Cohort2.0
## Name: Umar Lawan Sani
### Email: umarfarouq447@gmail.com
### Title: Week 1 Solution
## Exercises Solution

# 00. PyTorch Fundamentals Exercises
### 1. Documentation reading
A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):

- The documentation on torch.Tensor.
- The documentation on torch.cuda.

In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [ ]:
# Import torch
import torch
# Create random tensor
random_tensor = torch.rand((7, 7))
random_tensor


tensor([[0.0432, 0.8640, 0.4119, 0.5222, 0.9340, 0.2950, 0.8172],
        [0.9627, 0.3892, 0.1071, 0.4386, 0.4793, 0.0640, 0.1133],
        [0.7022, 0.6795, 0.8385, 0.1983, 0.3517, 0.6646, 0.7673],
        [0.5377, 0.4168, 0.3901, 0.9543, 0.8711, 0.5911, 0.6510],
        [0.5572, 0.2537, 0.9117, 0.3663, 0.4465, 0.7055, 0.5340],
        [0.7242, 0.9227, 0.0781, 0.3131, 0.0358, 0.5121, 0.0664],
        [0.5892, 0.6821, 0.9527, 0.7155, 0.4113, 0.0539, 0.0399]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [ ]:
# Create another random tensor
random_tensor_1 = torch.rand((1, 7))

random_tensor_1_transposed = random_tensor_1.T

# Perform matrix multiplication
result = torch.matmul(random_tensor, random_tensor_1_transposed)
result


tensor([[1.7682],
        [1.2676],
        [2.4266],
        [2.0114],
        [2.1235],
        [1.6236],
        [2.1965]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [ ]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
random_tensor = torch.rand((7, 7))

random_tensor_1 = torch.rand((1, 7))

random_tensor_1_transposed = random_tensor_1.T

# Matrix multiply tensors
result = torch.matmul(random_tensor, random_tensor_1_transposed)

print(result, result.shape)


tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]]) torch.Size([7, 1])


### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [ ]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)



### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [8]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# Create two random tensors on GPU
tensor_a = torch.rand((2, 3))
tensor_b = torch.rand((2, 3))

tensor_a_gpu = tensor_a.to(device)
tensor_b_gpu = tensor_b.to(device)

# Display the tensors and their device
print( tensor_a_gpu, tensor_a_gpu.device)
print( tensor_b_gpu, tensor_b_gpu.device)


tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0') cuda:0
tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]], device='cuda:0') cuda:0



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [9]:
# Perform matmul on tensor_A and tensor_B
result_gpu = torch.matmul(tensor_a_gpu, tensor_b_gpu.T)

# Display the result
print("Matrix Multiplication Result (on GPU):", result_gpu)

Matrix Multiplication Result (on GPU): tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0')


### 8. Find the maximum and minimum values of the output of 7.

In [10]:
# Find max
max = torch.max(result_gpu)

# Find min
min = torch.min(result_gpu)

print(max, min)


tensor(0.5617, device='cuda:0') tensor(0.3647, device='cuda:0')


### 9. Find the maximum and minimum index values of the output of 7.

In [12]:
# Find arg max
max_index = torch.argmax(result_gpu)

# Find arg min
min_index = torch.argmin(result_gpu)

print(max_index.item(), min_index.item())


3 0



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [13]:
# Set seed
torch.manual_seed(7)

# Create random tensor
tensor_4d = torch.rand((1, 1, 1, 10))


# Remove single dimensions
tensor_1d = tensor_4d.squeeze()


# Print out tensors and their shapes
print(tensor_4d, tensor_4d.shape)
print(tensor_1d, tensor_1d.shape)


tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
